### ISSUE TITLE
PA Review Auth

### ISSUE THREAD

**Issue by nmenares** [nmenares/KnittingWithStrangers#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by rkoron007** [comment]
First Off Super Adorable!!!!
- If I got to a random root like `/#/oweiniouewbrviuwebv` it will still render your footer but nothing else. I recommend having a hard redirect to your "/" splash page so that all your components are already there. 
![screen shot 2018-08-09 at 5 32 45 pm](https://user-images.githubusercontent.com/32436232/43932699-73f052a0-9bfa-11e8-9bbf-f19788a9f3a0.png)


- The yellow you used is a little brighter then the one on TeaWithStrangers - which is totally fine if that is a design choice, but it could also be nice as a little dimmer yellow. 
- Login form still says 'tea' - Here is the sentence: 'It's good to have you back. Sign in here and sign up for your next tea time!'
- The font style and spacing on your head navbar links could be formatted to closer to the original.
![screen shot 2018-08-09 at 5 38 06 pm](https://user-images.githubusercontent.com/32436232/43932818-07f60594-9bfb-11e8-9653-166b1fb9f5e6.png)

- Your Demo doesn't log you in on heroku(make sure you seeded so your user is there).

- On tea with Strangers they show their errors on the top of the page with a cute little banner. 

![screen shot 2018-08-09 at 5 42 14 pm](https://user-images.githubusercontent.com/32436232/43932927-a690213a-9bfb-11e8-8522-4f6fb2019974.png)

**Comment by rkoron007** [comment]
- I noticed that if I go to a random route it will still render your footer. I recommend having a hard redirect (like using the <Redirect> tag from react-router) to your "/" splash page so that all your components are already there. :)
- Maybe a little more spacing between you errors and header it looks a little crowded - but besides that it looks great!
![screen shot 2018-08-13 at 9 38 58 am](https://user-images.githubusercontent.com/32436232/44045253-cc422cd2-9edc-11e8-92d2-cf6dbe4775de.png)
